mate-desktop/engrampa

- caja/caja-engrampa.c
Fixes https://github.com/mate-desktop/engrampa/issues/78
This is a new feature on engrampa :)
The Patch:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800817
> Fixes: Cannot extract multiple files concurrently to a separate directory

- data/engrampa.1
> typo: modifing -> modifying

- src/fr-command-7z.c
> p7zip v9.38 or later with arg -spd

- src/fr-command-rar.c
> rar: avoid the message "No files to extract"

- src/fr-command-7z.c
file-roller commit:
https://git.gnome.org/browse/file-roller/commit/?id=d3ce6fe6964857c89212ab1a5a7aaa052d93c584
Fixes #138
> 7z: Fixed problems with files prefixed '@'

- src/fr-command-7z.c
isos for testing here:
http://slackware.uk/people/alien-slacklive/latest/
Fixes #128
> p7zip: ignore the error "Unexpected end of archive"

- src/fr-process.c
After https://github.com/mate-desktop/engrampa/commit/0b3b7eef61287213308e14639444e1953b52ac04 the compress with volumes doesn't work
This is the fix for 7z files, all the files will be move from the temp folder to the current folder at same time
Fixes partially #127 
and, the fix for rar volumes is pending
> Fix: compress 7z split into volumes

- src/fr-process.c
> Fix: compress rar split into volumes

- src/dlg-add-folder.c
- src/fr-window.c
This affects the add folder dialog and progress window.
> fix a few deprecations

- src/fr-window.c
- src/gtk-utils.c
- src/ui/add-options.ui
- src/ui/batch-add-files.ui
- src/ui/batch-password.ui
- src/ui/delete.ui
- src/ui/new.ui
- src/ui/password.ui
- src/ui/properties.ui
- src/ui/update.ui
Note, i am not really sure if all that ui files are used.....
> deprecation fixes

- src/fr-window.c
> hide folders in "View All Files"

- src/fr-window.c
- src/gtk-utils.c
- src/gtk-utils.h
> Dev gtk show uri

- src/fr-window.c
> fr-window: Replace deprecated gtk_menu_popup functions

- data/org.mate.engrampa.gschema.xml.in
- src/fr-command-7z.c
- src/fr-command-unarchiver.c
- src/fr-command-zip.c
Closes https://github.com/mate-desktop/engrampa/issues/210
> Add the ability to support 'unar' over .zip archives

- help/C/index.docbook
REF: https://cgit.freedesktop.org/xdg/shared-mime-info/tree/freedesktop.org.xml.in
> Manual: Update file format descriptions using shared-mime-info

- .travis.yml
Fix section name on `.travis.yml`
> [ci] fixed build phase's name

- caja/caja-engrampa.h
- caja/engrampa-module.c
- copy-n-paste/eggdesktopfile.c
- copy-n-paste/eggsmclient-xsmp.c
- copy-n-paste/eggsmclient.c
- src/dlg-add-files.c
- src/dlg-ask-password.c
- src/dlg-extract.c
- src/eggfileformatchooser.c
- src/fr-command-7z.c
- src/fr-command-lrzip.c
- src/fr-command-rar.c
- src/fr-command-tar.h
- src/fr-error.c
- src/fr-process.c
- src/fr-stock.c
- src/fr-window.c
- src/glib-utils.c
- src/gtk-utils.h
- src/java-utils.c
- src/java-utils.h
- src/open-file.c
`find . -regextype posix-extended -regex '.*\.(c|h|ac)' -exec sed --in-place 's/[[:space:]]\+$//' {} \+`
like rbuj do on [https://github.com/mate-desktop/mate-control-center/pull/463](https://github.com/mate-desktop/mate-control-center/pull/463).
> Remove trailing whitespaces

- src/glib-utils.c
- src/glib-utils.h
closes https://github.com/mate-desktop/engrampa/issues/283
> glib-utils: Remove unused function - g_ptr_array_copy

- src/Makefile.am
- src/gtk-utils.c
- src/gtk-utils.h
Unused since https://github.com/mate-desktop/engrampa/commit/0d3a5b087f4bb6c118abe34a14ea27b86583f812
> gtk-utils: Remove unused wrapper for gtk_builder_new_from_file

- caja/caja-engrampa.c
- src/actions.c
- src/dlg-new.c
- src/fr-command-ar.c
- src/fr-command-cpio.c
- src/fr-command-iso.c
- src/fr-command-lha.c
- src/fr-command-rpm.c
- src/fr-command-tar.c
- src/fr-command.c
- src/fr-stock.c
- src/fr-window.c
- src/typedefs.h
Remove 317 warnings [-Wdiscarded-qualifiers].
> Initialization discards ‘const’ qualifier from pointer target type

- src/glib-utils.c
- src/glib-utils.h
- src/gtk-utils.c
- src/gtk-utils.h
cppcheck --enable=unusedFunction .
> glib-utils & gtk-utils: Remove unused functions

- src/dlg-add-files.c
- src/eggfileformatchooser.c
- src/file-utils.c
- src/fr-process.c
- src/fr-window.c
- src/gio-utils.c
- src/java-utils.c
```C
void g_list_free_full (GList *list, GDestroyNotify free_func);
void g_slist_free_full (GList *list, GDestroyNotify free_func);
```
Convenience methods, which free all the memory used by a list,
and calls free_func on every element's data.
> Use g_list_free_full and g_slist_free_full

- caja/libcaja-engrampa.caja-extension.in.in
requires https://github.com/mate-desktop/caja/pull/1303
> i18n caja extension copyright

- src/dlg-prop.c
- src/ui/properties.ui
> Show archive type in properties dialog

- src/actions.c
> actions: expand the comment on about dialog

- src/dlg-update.c
> dlg-update: Fix callback names for callback symbol update_cb

- src/ui/update.ui
> update.ui: missing on_update_file_ok_button_clicked handler

- src/fr-archive.c
> fr-archive: Fix memory leak

- src/fr-command-rar.c
> rar 6.00: fix listing archive content with encrypted file list

- data/packages.match
- data/update-packages-match
https://github.com/GNOME/file-roller/commit/5e15ec065a0d79efe8cc1038c2d970b5a2b5b32b
> packages.match: add and run update-packages-match script

- src/fr-command-ar.c
Test:
```
$ touch -d "2021-02-01" 2021-02-01.txt
$ touch -d "2021-02-10" 2021-02-10.txt
$ ar r test.ar 2021-02-01.txt 2021-02-10.txt
$ engrampa test.ar
```
> ar: fix filename in file list

- src/fr-command-rar.c
test:
1 - install rar in /usr/local
```
$ wget https://www.rarlab.com/rar/rarlinux-x64-612.tar.gz
$ tar xzvf rarlinux-x64-612.tar.gz 
$ cd rar
$ sudo make install
```
2 - create test.rar archive
```
$ rar a test.rar rar
```
3 - open test.rar
```
$ engrampa test.rar
```
> fr-command-rar: parse date & time using strptime

- data/org.mate.engrampa.gschema.xml.in
- src/dlg-extract.c
- src/fr-window.c
- src/fr-window.h
- src/preferences.h
- src/ui/dlg-extract.ui
Add the function of automatically closing dialog after successful decompression
#388 
[2023年03月24日 屏幕视频 11时40分17秒.webm](https://user-images.githubusercontent.com/36913152/227419075-367636cb-c785-448a-aea5-5c07d1f636f5.webm)
> Add the function of automatically closing the dialog box after decompression

- src/fr-process.c
```
CFLAGS="-ggdb3 -O0 -fsanitize=address" LDFLAGS="-fsanitize=address" ./autogen.sh --prefix=/usr && make && sudo make install
```
```
Direct leak of 128 byte(s) in 1 object(s) allocated from:
#0 0x7fec22178cb8 in __interceptor_realloc (/lib64/libasan.so.6+0xaecb8)
#1 0x7fec210e02d7 in g_realloc ../glib/gmem.c:171
#2 0x7fec2108da30 in g_ptr_array_maybe_expand ../glib/garray.c:1525
#3 0x7fec2108e2d1 in g_ptr_array_add ../glib/garray.c:1834
#4 0x47d3b9 in fr_process_begin_command /home/robert/builddir.gcc/engrampa/src/fr-process.c:362
#5 0x465552 in begin_tar_command /home/robert/builddir.gcc/engrampa/src/fr-command-tar.c:228
#6 0x4655f3 in fr_command_tar_list /home/robert/builddir.gcc/engrampa/src/fr-command-tar.c:239
#7 0x447499 in fr_command_list …
```
> fr-process: fix memory leak

- src/actions.c
- src/actions.h
- src/fr-window.c
- src/fr-window.h
- src/ui.h
```sort_by_entries``` Not appearing in any UI file, users cannot use these sorting options, so this is useless code
> action: Delete unused sort_by_entries code

- src/fr-window.c
Fix #344 
```
[test@localhost engrampa]$ lsblk  /dev/sda1 
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda1   8:1    1 149.5M  0 part /mnt
[test@localhost engrampa]$ du -sh /tmp/mate-user-guide
190M	/tmp/mate-user-guide
[test@localhost engrampa]$ zip -r /tmp/mate-user-guide.zip /tmp/mate-user-guide/ -q
[test@localhost engrampa]$ du -sh /tmp/mate-user-guide.zip 
65M	/tmp/mate-user-guide.zip
[test@localhost engrampa]$ sudo  ./src/engrampa /tmp/mate-user-guide.zip -e /mnt/
```
> Check if the remaining disk space is sufficient when add extract

- src/glib-utils.c
Fix https://github.com/mate-desktop/engrampa/issues/496
> Fix Segfault on opening .deb files after recent Debian Unstable updates

- src/ui/menus-toolbars.ui
- reported by translators https://app.transifex.com/mate/MATE/translate/#id/master--engrampa/470908044
> correct translation string

- src/file-utils.c
> Replace special "#" and "?" characters in uri

- src/fr-process.c
Fix https://github.com/mate-desktop/engrampa/issues/510
> fr-process.c: Setting error status
