mate-desktop/engrampa

src/fr-window.c
This reduce the size of the statusbar that it looks like GTK2 version.
The size can now controled with .frame.flat and/or .flat.button selector
by the theme.
=> GTK3: set top and bottom margin of statusbar to zero

src/fr-command-rar.c
adapted from
https://github.com/GNOME/file-roller/commit/8c55a4118dc83f171ca89407492269ecfe0a20d3
=> fr-command-rar: additional check for NULL pointer to avoid crash

src/Makefile.am
adapted from
https://git.gnome.org/browse/file-roller/commit/?id=bcc2b505e564161428fa1115d7f7858244a5fed3
=> fix wrong header guard in generated src/fr-enum-types.h

src/fr-command-unarchiver.c
Fixes issues with special char '?' extracting files with unar
=> The char '?' needs to be escaped

src/fr-archive.c, src/glib-utils.c
The patch on file-roller:
https://bugzilla.gnome.org/show_bug.cgi?id=761582
Fixes #125
=> fix extracting files with single-character names. #125

src/dlg-new.c
Fixes #132 
Here is the commit on file-roller:
https://git.gnome.org/browse/file-roller/commit/?id=c2a838af1bb7c6df48be31c02bcfee5fe243d538
=> 'All files' is duplicated in available formats

src/fr-command-tar.c
Fixes #79
using --no-unquote
do not unquote input file or member names
=> tar: Fixed problems with backslashes

src/fr-init.c
At the moment p7zip does not support RAR5 archives, so reading such archives will always fail.
=> Give unrar priority over p7zip

src/fr-window.c
This adds 'engrampa-window' at top and the 'frame' style class to the scrolledwindows.
scrolledwindow.frame is used to set a border in most themes.
Adding a specific class at top of the code of an application is always a good idea.
At the moment i need this, as i have to set a border on 'frame > border' for firefox in themes to have a border for the locationbar.
See https://github.com/flexiondotorg/ubuntu-mate-themes/issues/35
In result i can remove the border here with
```
.engrampa-window > grid > paned > box > frame > border {
border-style: none;
}
```
=> add some style class

src/fr-window.c
Fixes #167
based in file-roller commit:
https://git.gnome.org/browse/file-roller/commit/?id=bd8807beb9a026be2441aa492815b65a6fc94429
=> Fix: Browsing history not correct

src/fr-command-7z.c
based in file-roller commit:
https://git.gnome.org/browse/file-roller/commit/?id=f9b8a010e7fe5a9bec158dfc5bd8ef1e11bf3842
Fixes:
https://bugs.launchpad.net/ubuntu/+source/engrampa/+bug/1580860
=> Fix: create zip files in "maximum" compression level

src/fr-window.c
New feature
Fixes #146 
without this PR:
with this PR:
=> Add the button "Show the Files and Quit" in the progress dialog

src/dlg-open-with.c
Steps to reproduce:
- open some archive
- right-click on some file and choose Open With
- either open file with some app, or just close the dialog (cancel)
- exit Engrampa
Without the fix, it will crash on exit with double-free error. The patch removes excessive freeing of GList which contains the list of files.
=> fix crash on exit after using Open With dialog

src/ui/properties.ui
the Close button, not the Help button, should be the one set to default so that you can press Enter or Space without unintentionally opening the help manual
=> UI: on the properties dialog, focus the Close button by default

src/fr-window.c
Real fix for https://github.com/mate-desktop/engrampa/pull/216
Test with generating engrampa.pot in main dir.
`./autogen.sh && ./makepot`
After merging engrampa.pot can be updated and commited in github.
The resource file at transifex will be automatic updated from git.
And translators can update translations.
=> fr-window: fix typo

src/dlg-package-installer.c
Any `real_name` which was found was not getting used before.
Also, when the lookup is unsuccessful, this means there is no
_alternative_ package name.  Thus we should use the hard-coded package
name as the real_name for our PackageKit installation request.
[bug #603757]
origin commit: https://gitlab.gnome.org/GNOME/file-roller/commit/95aafc3c
=> Fix implementation and use of the alternative package name lookup

src/fr-window.c
=> fr-window: change the info label if process is paused/resumed

src/fr-window.c
Fixes this issue:
The pause button must be hidden here
How to show this dialog? with the button "extract" in the toolbar, or with "archive" -> "extract" in menus.
=> fr-window: show the pause button only if the dialog is working

data/engrampa.1, src/main.c
This adds a `--version` flag to the engrampa cli.
Fixes #248
=> Show version on command line

help/C/index.docbook, help/C/legal.xml, help/engrampa.pot
To upgrade the manual:
sudo dnf install -y docbook5-schemas
xsltproc --output index-new.docbook /usr/share/xml/docbook5/stylesheet/upgrade/db4-upgrade.xsl index.docbook
xsltproc --output legal-new.xml /usr/share/xml/docbook5/stylesheet/upgrade/db4-upgrade.xsl legal.xml
To validate the manual:
xmllint --noout --relaxng /usr/share/xml/docbook5/schema/rng/5.0/docbook.rng help/C/index.docbook
jing /usr/share/xml/docbook5/schema/rng/5.0/docbook.rng help/C/index.docbook
yelp-check validate help/C/index.docbook
To view the manual:
yelp file:///full_path/index.docbook
Note: docbook5-schemas should be installed in your system in order to view the manual (DEPENDENCY)
=> Upgrade the manual to docbook 5.0

src/fr-process.c
Fixes Clang static analyzer warning:
fr-process.c:740:3: warning: Potential leak of memory pointed to by 'argv'
g_warning ("The files could not be move: %s\n", commandline);
^~~~~~~~~
=> fr-process: Fix memory leak

src/fr-process.c
Use 'g_strlcpy' instead of 'strcpy', and 'g_strlcat' instead of 'strcat'
Fixes Clang static analyzer warnings:
```
fr-process.c:696:5: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
strcpy(rarfile, argv[2]);
^~~~~~
fr-process.c:698:5: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119
strcat(rarfile, "part1.rar");
^~~~~~
fr-process.c:705:32: warning: Out of bound memory access (accessed memory precedes memory block)
rarfile[strlen(rarfile)-5]=0; …
```
=> [Security] fr-process: avoid 'strcpy' and 'strcat'

src/fr-process.c
- First commit:
`g_strconcat` needs to be freed:
https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strconcat
Use `GString` instead `g_strconcat`
- Second commit:
`g_shell_quote` needs to be freed
https://developer.gnome.org/glib/unstable/glib-Shell-related-Utilities.html#g-shell-quote
- How to test:
check if the compress with multiple volumes with `7z` and/or `rar` works as before
=> fr-process: Fix memory leaks

src/actions.c
Fixes Clang static analyzer warning:
```
actions.c:137:5: warning: Use of memory after it is freed
return full_uri;
^~~~~~~~~~~~~~~
```
=> actions: avoid use of memory after it is freed

src/file-utils.c
Fixes Clang static analyzer warning:
```
file-utils.c:453:6: warning: Out of bound memory access (access exceeds upper limit of memory block)
if (file_name [last_char] == G_DIR_SEPARATOR)
^~~~~~~~~~~~~~~~~~~~~
```
=> file-utils: avoid out of bound memory access

help/C/index.docbook
Yelp viewer can't open cross-references to other parts of
the manual using link linkend.
=> Help: replace link linkend with xref linkend

src/eggfileformatchooser.c
```
eggfileformatchooser.c: 在函数‘egg_file_format_chooser_class_init’中:                                                                                                   
eggfileformatchooser.c:794:3: 警告：‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]                                                                
g_type_class_add_private (cls, sizeof (EggFileFormatChooserPrivate));                                                                                                
^~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                             
```
=> Avoid deprecated g_type_class_add_private

src/fr-command-unarchiver.c
without this PR:
with this PR:
file to test (inside the .zip): [testing.zip](https://github.com/mate-desktop/engrampa/files/3388907/testing.zip) password 123
In the tests, make sure the packages `rar` and `unrar` aren't installed, and make sure the package `unar` is installed.
=> fr-command-unarchiver: ask password if required

src/fr-window.c
Fixes `cppcheck` warnings:
```
[src/fr-window.c:269]: (style) struct member '_FrWindowPrivateData::tree_hover_path' is never used.
[src/fr-window.c:349]: (style) struct member '_FrWindowPrivateData::mitem_recents_menu' is never used.
```
=> fr-window: remove unused struct members

src/main.c
Detected by clang static analyzer:
```
$ scan-build -enable-checker alpha.deadcode.UnreachableCode --keep-cc -o html-report make
...
exit (EXIT_SUCCESS);
return TRUE; /* <= This statement is never executed */
...
```
=> return sentence won't be never executed as it's preceded by exit

src/dlg-prop.c, src/fr-archive.c, src/fr-command-unarchiver.c, src/fr-init.c, src/fr-window.c, src/java-utils.c
Fix compiler warning:
comparison of integers of different signs: 'int' and 'guint' (aka 'unsigned int') [-Wsign-compare]
=> comparison of integers of different signs: 'int' and 'guint'

src/java-utils.c
java-utils.c:310:23: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
=> comparison of unsigned expression >= 0 is always true

src/fr-command.h
fr-command.h:205:16: warning: redundant redeclaration of ‘fr_command_is_capable_of’ [-Wredundant-decls]
=> Redundant redeclaration of ‘fr_command_is_capable_of’

src/fr-command-lrzip.c
str is empty: if (*str == '\0') {...}
=> fr-command-lrzip: Fix empty string check

src/java-utils.c
Closes https://github.com/mate-desktop/engrampa/issues/291
Test:
```
touch test.txt
zip test.zip test.txt
mv test.zip test.jar
cat << EOF > HelloWorld.java
package org.mate.tests;
class HelloWorld
{
public static void main(String args[])
{
System.out.println("Hello, World");
}
}
EOF
engrampa -a test.jar HelloWorld.java
jar tf ~/test.jar
```
Output:
```
test.txt
org/mate/tests/HelloWorld.java
```
=> java-utils: Remove blank spaces before reading package name

caja/caja-engrampa.c, src/actions.c, src/dlg-add-files.c, src/fr-window.c
actions.c:245:24: warning: declaration of ‘dialog’ shadows a previous local [-Wshadow]
caja-engrampa.c:137:17: warning: declaration of ‘file’ shadows a previous local [-Wshadow]
caja-engrampa.c:58:17: warning: declaration of ‘file’ shadows a previous local [-Wshadow]
dlg-add-files.c:120:9: warning: declaration of ‘uri’ shadows a previous local [-Wshadow]
fr-window.c:4935:11: warning: declaration of ‘value’ shadows a previous local [-Wshadow]
Test:
```bash
#!/bin/bash
CFLAGS="-g -O -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wendif-labels -Wformat=2 -Winit-self -Wswitch-enum -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-align -Wwrite-strings -Wjump-misses-init -Wlogical-op -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wnested-externs -Wundef -Wformat-security" ./autogen.sh …
```
=> remove build warning: local variable shadows another variable

src/dlg-batch-add.c, src/dlg-new.c, src/typedefs.h
```
dlg-batch-add.c:513:83: warning: cast from function call of type ‘gint’ {aka ‘int’} to non-matching type ‘double’ [-Wbad-function-cast]
513 |  gtk_spin_button_set_value (GTK_SPIN_BUTTON (GET_WIDGET ("a_volume_spinbutton")), (double) g_settings_get_int (data->settings, PREF_BATCH_ADD_VOLUME_SIZE) / MEGABYTE);
|                                                                                   ^
dlg-new.c:321:81: warning: cast from function call of type ‘gint’ {aka ‘int’} to non-matching type ‘double’ [-Wbad-function-cast]
321 |         gtk_spin_button_set_value (GTK_SPIN_BUTTON (data->n_volume_spinbutton), (double) g_settings_get_int (settings, PREF_BATCH_ADD_VOLUME_SIZE) / MEGABYTE);
|                                                                                 ^
```
```shell
$ echo …
```
=> remove warnings: cast from function call [-Wbad-function-cast]

caja/caja-engrampa.c, src/eggtreemultidnd.c, src/fr-archive.c, src/fr-command-7z.c, src/fr-command-ace.c, src/fr-command-alz.c, src/fr-command-ar.c, src/fr-command-arj.c, src/fr-command-cfile.c, src/fr-command-cpio.c, src/fr-command-dpkg.c, src/fr-command-iso.c, src/fr-command-jar.c, src/fr-command-lha.c, src/fr-command-lrzip.c, src/fr-command-rar.c, src/fr-command-rpm.c, src/fr-command-tar.c, src/fr-command-unarchiver.c, src/fr-command-unstuff.c, src/fr-command-zip.c, src/fr-command-zoo.c, src/fr-command.c, src/fr-list-model.c, src/fr-process.c, src/fr-window.c, src/ui.h
caja-engrampa.c:439:2: warning: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Wmissing-field-initializers]
eggtreemultidnd.c:70:2: warning: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Wmissing-field-initializers]
fr-command.c:98:3: warning: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘struct _GTypeInfo’} [-Wmissing-field-initializers]
fr-command-7z.c:750:3: warning: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘struct _GTypeInfo’} [-Wmissing-field-initializers]
fr-command-ace.c:334:3: warning: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘struct _GTypeInfo’} [-Wmissing-field-initializers]
fr-command-alz.c:397:3: warning: missing …
=> Missing initializer for struct field

src/fr-archive.c
fr-archive.c:45:5: warning: "ENABLE_MAGIC" is not defined, evaluates to 0 [-Wundef]
fr-archive.c:519:5: warning: "ENABLE_MAGIC" is not defined, evaluates to 0 [-Wundef]
=> remove warnings: "ENABLE_MAGIC" is not defined, evaluates to 0

src/fr-command-tar.c
=> tar: don't remove leading whitespaces in filename field

src/fr-command-ace.c
closes #303
Before:
After:
```shell
$ unace v -y ~/test.ace 
UNACE v2.5     Copyright by ACE Compression Software       Jun 18 2017 19:18:45
processing archive /home/robert/test.ace                                  
Main comment                                                              
This is a comment.
created on 8.9.2019 with ver 2.0 by                                       
*UNREGISTERED VERSION*                                                    
Contents of archive test.ace                                              
Date    Time     Packed      Size  Ratio  File                          
08.09.19 21:32           0         0    0%  test/folder/blank             
08.09.19 21:29          13        13  100%  test/README.txt               
listed: 2 files, totaling 13 bytes …
```
=> unace 2.5: Don't show archive summary in file listing

src/dlg-prop.c, src/fr-window.c, src/glib-utils.c, src/glib-utils.h
`get_time_string()` is a local function that wraps `strftime()`. In contrast to `strftime()`, `g_date_time_format()` always produces a UTF-8 string, regardless of the current locale.
=> glib-utils: Remove get_time_string

src/dlg-package-installer.c
```
dlg-package-installer.c:294:9: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
294 |         GTK_STOCK_DIALOG_ERROR,
|         ^~~~~~~~~~~~~~~~~~~~~~
dlg-package-installer.c:297:9: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
297 |         GTK_STOCK_CANCEL, GTK_RESPONSE_NO,
|         ^~~~~~~~~~~~~~~~
```
=> dlg-package-installer: remove warning ‘GtkStock’ is deprecated

src/dlg-add-folder.c, src/fr-window.c, src/gtk-utils.c
```
gtk-utils.c:171:3: warning: ‘gtk_image_new_from_stock’ is deprecated: Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
171 |   image = gtk_image_new_from_stock (text, GTK_ICON_SIZE_BUTTON);
|   ^~~~~
gtk-utils.c:173:3: warning: ‘gtk_image_new_from_stock’ is deprecated: Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
173 |   image = gtk_image_new_from_stock (stock_id, GTK_ICON_SIZE_BUTTON);
|   ^~~~~
```
=> remove warnings: ‘gtk_image_new_from_stock’ is deprecated

src/dlg-prop.c
Based on https://github.com/GNOME/file-roller/commit/9a37eb44a8ec5d0a20ea78c9a44c7c9e50bb508f#diff-41f5e2a364a93ff790f678ba58265d43
=> dlg-prop: allow to open the archive's folder

src/fr-command-lha.c
gio returns "application/x-lha" in get_mime_type_from_content
test:
```
$ gio info test.lzh | grep content-type
standard::content-type: application/x-lha
standard::fast-content-type: application/x-lha
$ grep x-lha /usr/share/mime/packages/* 
/usr/share/mime/packages/freedesktop.org.xml:  <mime-type type="application/x-lha">
```
file and xdg-mime return the current Lha mimetype, application/x-lha is an alias.
```shell
$ file -b --mime-type test.lzh 
application/x-lzh-compressed
$ xdg-mime query filetype test.lzh 
application/x-lzh-compressed
```
=> LHA: make compatible with content-type response from gio file query

src/fr-command-ar.c
test:
```shell
$ touch " test"
$ touch "  test"
$ ar r test.a " test" "  test"
$ ar tv test.a
rw-rw-r-- 1000/1001	 0 Sep 18 14:58 2019  test
rw-rw-r-- 1000/1001	 0 Sep 18 14:58 2019   test
$ engrampa test.a
```
=> ar: don't remove leading whitespaces in filename field

.travis.yml, caja/Makefile.am, configure.ac, copy-n-paste/Makefile.am, src/Makefile.am, src/commands/Makefile.am
USAGE: ./autogen.sh --enable-compile-warnings=no/minimum/yes/maximum/error@
If --enable-compile-warnings is not provided, the default is --enable-compile-warnings=yes
It requires https://github.com/mate-desktop/mate-common/pull/27, plus autoconf-archive package on build.
=> Use mate-compiler-flags.m4 provided by mate-common

src/fr-archive.c
```
$ file -b --mime-type ~/test.tar.Z
application/x-compress
$ hexdump -C -n 2 ~/test.tar.Z
00000000  1f 9d                                             |...|
00000002
```
```
$ file -b --mime-type ~/atril-1.23.1-1.fc30.src.rpm
application/x-rpm
$ hexdump -C -n 4 ~/atril-1.23.1-1.fc30.src.rpm
00000000  ed ab ee db                                       |....|
00000004
```
```
$ file -b --mime-type ~/test.lzh
application/x-lzh-compressed
$ hexdump -C -s 2 -n 3 ~/test.lzh
00000002  2d 6c 68                                          |-lh|
00000005
```
=> Add application/(x-compress|x-rpm|x-lzh-compressed) in local magic

caja/caja-engrampa.c, configure.ac, src/fr-archive.c, src/fr-command-cfile.c, src/fr-command.c, src/fr-command.h, src/fr-process.c, src/fr-window.c, src/glib-utils.c, src/java-utils.c
test:
```
$ ./autogen.sh --enable-debug=profile --prefix=/usr
<cut>
Configuration:
Source code location:   .
Compiler:               gcc
Compiler flags:          -g -pg
Warning flags:          -Wall -Wmissing-prototypes
Linker flags:            -pg
Caja support:           yes
PackageKit support:     yes
Run in place            no
Use libmagic:           no
JSON support:           yes
Now type `make' to compile engrampa
```
test:
```
$ ./autogen.sh --enable-debug --prefix=/usr
<cut>
Configuration:
Source code location:   .
Compiler:               gcc
Compiler flags:          -g -O0
Warning flags:          -Wall -Wmissing-prototypes
Linker flags:           
Caja support:           yes
PackageKit support:     yes
Run in place            no
Use libmagic:           no
JSON support: …
```
=> Set compiler debug flags using MATE_DEBUG_CHECK and update configure summary

.travis.yml
Fixes debian travis build
@mate-desktop/core-team if you agree, I will do the same in all the repositories to the master and 1.22 branches.
Debian testing have packages more tested, and give us less problems.
=> Travis CI: use Debian "testing" instead "sid"

src/fr-window.c
Pause/Resume button doesn't update the UI state on non-English localized environments. This fixes it for my language, and hopefully for all the others too.
=> Fix localized pause UI logic

src/fr-init.c
For instance, application/x-lha is an alias of application/x-lzh-compressed,
mime_type_desc.mime_type should only store non duplicated primary mime-types,
to avoid duplicates in the warehouse.
=> Check if a mime-type is an alias in compute_supported_archive_types

src/fr-command-7z.c
closes https://github.com/mate-desktop/engrampa/issues/200
=> 7z: Don't set the work directory, i.e. use temporary directory

src/fr-process.c
Closes #354
Test:
```shell
[robert@localhost engrampa]$ CFLAGS="-g -O0" ./autogen.sh --prefix=/usr --enable-debug && make && sudo make install
<cut>
[robert@localhost engrampa]$ engrampa /home/robert/テスト.rar
```
Before
```shell
[FR] fr-window.c:2905 (action_started):
LOADING_ARCHIVE [START] (FR::Window)
[FR] fr-window.c:3207 (action_performed):
LOADING_ARCHIVE [DONE] (FR::Window)
[FR] fr-command.c:589 (fr_command_set_filename):
filename : /home/robert/テスト.rar
[FR] fr-command.c:590 (fr_command_set_filename):
e_filename : '/home/robert/テスト.rar'
[FR] fr-archive.c:697 (action_started):
LISTING_CONTENT [START] (FR::Archive)
[FR] fr-window.c:2905 (action_started):
LISTING_CONTENT [START] (FR::Window)
[FR] fr-process.c:682 (start_current_command):
0/0) 
LC_ALL=C
unrar v -c- -v -p- -- …
```
=> fr-process: do not override LC_CTYPE

src/main.c
```
/usr/bin/ld: main.o:(.bss+0x0): multiple definition of `ForceDirectoryCreation'; fr-init.o:(.bss+0x8): first defined here
```
=> Fix build using gcc 10 -fno-common flag

src/dlg-batch-add.c
Test:
- left-click on any folder in caja window
- click on Compress...
Compress dialog is shown, displaying the package image on the left
=> dlg-batch-add: set dialog image from icon-name instead of pixbuf

.build.yml, .travis.yml
I think we don't need to sync `mate-desktop.dev` website with stable branch
=> [1.24] Travis CI: don't update gh-pages

src/fr-command.c, src/glib-utils.c, src/glib-utils.h
Removed warnings:
```
fr-command.c:548:39: warning: cast between incompatible function types from ‘void (*)(FileData *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
548 |   g_ptr_array_free_full (comm->files, (GFunc) file_data_free, NULL);
|                                       ^
--
fr-command.c:627:39: warning: cast between incompatible function types from ‘void (*)(FileData *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
627 |   g_ptr_array_free_full (comm->files, (GFunc) file_data_free, NULL);
|                                       ^
```
=> glib-utils: remove g_ptr_array_free_full

src/fr-window.c, src/gtk-utils.c, src/gtk-utils.h
Removed warnings:
```
gtk-utils.c:32:31: warning: unused parameter ‘model’ [-Wunused-parameter]
32 | count_selected (GtkTreeModel *model,
|                 ~~~~~~~~~~~~~~^~~~~
gtk-utils.c:33:17: warning: unused parameter ‘path’ [-Wunused-parameter]
33 |   GtkTreePath  *path,
|   ~~~~~~~~~~~~~~^~~~
gtk-utils.c:34:17: warning: unused parameter ‘iter’ [-Wunused-parameter]
34 |   GtkTreeIter  *iter,
|   ~~~~~~~~~~~~~~^~~~
```
=> gtk-utils: Remove _gtk_count_selected

src/dlg-add-files.c, src/dlg-add-folder.c, src/dlg-ask-password.c, src/dlg-batch-add.c, src/dlg-delete.c, src/dlg-extract.c, src/dlg-new.c, src/dlg-password.c, src/dlg-prop.c, src/dlg-update.c, src/gtk-utils.c, src/gtk-utils.h
It terminates engrampa and it shows the message below when the RESOURCE doesn't exist:
```
(engrampa:25129): Gtk-ERROR **: 23:11:24.338: failed to add UI: The resource at “/org/mate/Engrampa/ui/RESOURCE” does not exist
Trace/breakpoint trap (core dumped)
```
It removes the warnings below:
GCC 10 analyzer:
```
$ CFLAGS="-fanalyzer" ./autogen.sh --prefix=/usr && make
```
warnings:
```
In function ‘dlg_new’:
dlg-new.c:426:40: warning: dereference of NULL ‘data’ [CWE-690] [-Wanalyzer-null-dereference]
426 |  gtk_window_set_title (GTK_WINDOW (data->dialog), C_("File", "New"));
/usr/include/glib-2.0/gobject/gtype.h:2301:57: note: in definition of macro ‘_G_TYPE_CIC’
2301 |     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
| …
```
=> Terminate the application if the resource doesn't exists

.travis.yml
https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release#cleaning-up-the-git-working-directory
=> Travis CI: avoid deprecated skip_cleanup

help/C/index.docbook
Correction and updating of some archive format names in the user guide.
[Reference](https://www.gnu.org/software/tar/manual/html_section/tar_68.html).
=> fix and update archive format names

.travis.yml
This PR enables `irc` notifications on `#mate-dev` channel at freenode if the build in `master` branch fails, if the build is ok, it does nothing (to avoid the noise).
How to test: feel free to put here one more commit with the change:
```
-    if: branch = master AND
+    if: branch = travistest AND
```
and with one more little change to force the build to fail and see the #mate-dev channel.
revert the broken change to force the build ok, and see it doesn't notify to channel.
and finally keep the PR in the original state
If accepted I will do the same in all the repositories, and in stable branches
=> Travis CI: enable irc notifications with broken builds

README
After git submodule use, git is now need to compile Engrampa from the source code.
Added git in the dependencie section.
Added "git submodule init && git submodule update" command in the installation section.
=> Update compilation instructions

src/java-utils.c
g_strndup allocated the memory for the second time without releasing it
I understand my way of fixing the issue is not perfect so I'd love to hear your suggestions on it
=> Avoid memory leak in java utils

src/fr-command-unarchiver.c
```
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/[[:space:]]*$//' {} \;
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/\t*$//' {} \;
```
=> Remove trailing spaces

caja/caja-engrampa.c, src/eggfileformatchooser.c, src/eggtreemultidnd.c, src/file-data.c, src/file-utils.c, src/fr-archive.c, src/fr-command-cpio.c, src/fr-command-iso.c, src/fr-command-lha.c, src/fr-command-rpm.c, src/fr-window.c, src/gtk-utils.c
```
caja/caja-engrampa.c:113:20: style: The scope of the variable 'quoted_uri' can be reduced. [variableScope]
char             *quoted_uri, *quoted_dir;
^
mate-submodules/libegg/eggdesktopfile.c:497:9: style: The scope of the variable 'try_exec' can be reduced. [variableScope]
char *try_exec, *found_program;
^
mate-submodules/libegg/eggdesktopfile.c:497:20: style: The scope of the variable 'found_program' can be reduced. [variableScope]
char *try_exec, *found_program;
^
mate-submodules/libegg/eggdesktopfile.c:498:10: style: The scope of the variable 'only_show_in' can be reduced. [variableScope]
char **only_show_in, **not_show_in;
^
mate-submodules/libegg/eggdesktopfile.c:498:26: style: The scope of the variable 'not_show_in' can be reduced. [variableScope]
char **only_show_in, …
```
=> Remove cppcheck warnings about the variable scope can be reduced

caja/Makefile.am, caja/libcaja-engrampa.caja-extension.desktop.in.in, configure.ac, data/Makefile.am, data/engrampa.appdata.xml.in.in, po/POTFILES.in, src/actions.c
Test:
```
$ grep Website caja/libcaja-engrampa.caja-extension
Website=https://mate-desktop.org
$ grep PACKAGE_URL config.h
#define PACKAGE_URL "https://mate-desktop.org"
$ grep homepage data/engrampa.appdata.xml
<url type="homepage">https://mate-desktop.org</url>
```
- Set all [AC_INIT](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Initializing-configure.html) fields including optional ones (configure.ac):
```
Macro: AC_INIT (package, version, [bug-report], [tarname], [url])
```
- Do not include the generated files `$(desktop_DATA)`and `$(desktop_in_files)` in `EXTRA_DIST` (data/Makefile.am)
=> build: Use PACKAGE_URL variable

Makefile.am, caja/Makefile.am, configure.ac, data/Makefile.am, help/Makefile.am, src/dlg-update.c, src/fr-window.c, src/main.c, src/server.c
```
$ find /usr/share/locale -type f -name 'engrampa.mo' -exec sudo rm -f {} +
$ find /usr/share/help -type d -name 'engrampa' -exec sudo rm -fr {} +
$ ./autogen.sh --prefix=/usr && make && sudo make install
$ find /usr/share/locale -type f -name 'engrampa.mo' -exec du -ch {} + | grep total
2,9M	total
$ find /usr/share/help -type d -name 'engrampa' -exec du -ch {} + | grep total
12M	total
```
```
$ find /usr/share/locale -type f -name 'engrampa.mo' -exec sudo rm -f {} +
$ find /usr/share/help -type d -name 'engrampa' -exec sudo rm -fr {} +
$ ./autogen.sh --prefix=/usr --disable-nls && make && sudo make install
$ find /usr/share/locale -type f -name 'engrampa.mo' -exec du -ch {} + | grep total
$ find /usr/share/help -type d -name 'engrampa' -exec du -ch {} + | grep total
136K	total
```
=> build: allow users to disable gettext support (--disable-nls)

data/Makefile.am
The variable `appdata_DATA` is set to `engrampa.appdata.xml`
=> build: don't add twice the file engrampa.appdata.xml to CLEANFILES

src/fr-command-alz.c
```
fr-command-alz.c:292:19: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
if ((error->type == FR_PROC_ERROR_STOPPED)) {
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
fr-command-alz.c:292:19: note: remove extraneous parentheses around the comparison to silence this warning
```
=> equality comparison with extraneous parentheses

src/glib-utils.c, src/glib-utils.h
The function is only used in escape_str_common.c and it's called after its implementation.
=> glib-utils: escape_str_common should be static

src/main.c, src/server.c
```
main.c:92:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL }
^
--
server.c:393:1: warning: missing field 'padding' initializer [-Wmissing-field-initializers]
};
^
```
=> Fix build warnings about missing field initializer

src/fr-process.c, src/fr-window.c, src/fr-window.h
```
git submodule init
git submodule update --recursive --remote
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
fr-process.c:416:17: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
info->sticky = sticky;
~ ^~~~~~
fr-process.c:429:23: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
info->ignore_error = ignore_error;
~ ^~~~~~~~~~~~
--
fr-window.c:6433:7: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'FrOverwrite' [-Wsign-conversion]
overwrite,
^~~~~~~~~
```
=> Fix implicit conversion changes signedness: 'gboolean'

src/fr-window.c
```
fr-window.c:5779:33: warning: incompatible pointer types passing 'GtkWidget *' (aka 'struct _GtkWidget *') to parameter of type 'GtkLabel *' (aka 'struct _GtkLabel *') [-Wincompatible-pointer-types]
gtk_label_set_mnemonic_widget (window->priv->location_label,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/gtk-3.0/gtk/gtklabel.h:129:70: note: passing argument to parameter 'label' here
void     gtk_label_set_mnemonic_widget            (GtkLabel         *label,
^
```
=> fr-window: fix -Wincompatible-pointer-types warning

src/glib-utils.c
```
$ cppcheck --enable=all --quiet . &> cppcheck.log
$ grep -A 2 redundantCondition cppcheck.log 
src/glib-utils.c:366:24: style: Redundant condition: If 'EXPR == ' '', the comparison 'EXPR != 0' is always true. [redundantCondition]
while ((*line == ' ') && (*line != 0))
^
```
=> glib-utils: redundant condition

src/actions.c, src/dlg-new.c, src/dlg-new.h, src/fr-window.c
Fix archive file save as functio. When saving as, it will check whether the two archive files are the same
#414
=> Fix archive file save as function

src/fr-command-rar.c
```
cppcheck --enable=all --quiet . &> cppcheck.log
grep constParameter cppcheck.log 
```
=> fr-command-rar: Parameter 'line' can be declared with const

src/dlg-batch-add.c
Fix icon missing when compressing files with the right mouse button
#412
=> Fix icon missing when compressing files with the right mouse button

src/file-utils.c
The _XOPEN_SOURCE macro definition overrides _DEFAULT_SOURCE and disables the declaration in <string.h>.
This avoids an implicit function declaration and build failures with future compilers.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
=> file-utils: Include <strings.h> for strcasecmp

src/main.c
Fix #245
```
[Session]
archive0=file:///tmp/ssss.7z
archives=1
```
```
i = g_key_file_get_integer (state, "Session", "archives", NULL); = 1;
for (; i > 0; i--) {
key = g_strdup_printf ("archive%d", i) = "archive1";
archive = g_key_file_get_string (state, "Session", "archive1", NULL) = NULL;
g_free (key);
if (strlen (archive)) /*strlen (NULL)*/
fr_window_archive_open (FR_WINDOW (window), archive, GTK_WINDOW (window));
}
```
This can cause memory crash
=> Fix failed restore of saved sessions

src/gio-utils.c, src/gio-utils.h
```g_file_enumerate_children_async``` default should use ```G_FILE_QUERY_INFO_NOFOLLOW_SYMLINKS```. This can avoid link loops
Fix #254 
```
mkdir /tmp/test
cd /tmp/test
for x in $( seq 1 1000 ); do mkdir test${x}; touch test${x}/${x}; done
mkdir test1001
cd test1001
ln -s ../ new
engrampa -d /tmp/test
```
The number of archived files should be 2003
=> Archive: do not track symbolic link

src/ui/new.ui
The file chooser dialog margin size should remain the same， Open、New、Extract
Fix #184
=> Uniform file chooser dialog margin size

src/glib-utils.c
[05-13-2023Screen video05^%41^%24 PM.webm](https://github.com/mate-desktop/engrampa/assets/36913152/c2b8e2cc-fe05-4fe0-9d04-0b64d1975ed9)
Fix failure to extract multiple files
Fix #371 
```
mkdir /tmp/test
cd /tmp/test
touch test{1,2,3}.file
find -type f -name test"*"file -execdir tar -zcvf '{}.tar.gz' '{}' \; | xargs rm -rf
engrampa -f *.gz
```
=> Fix failure to extract multiple files

src/dlg-extract.c
=> Set the current folder of the file chooser dialog using a local file name

src/file-utils.c, src/fr-archive.c, src/fr-init.c
Referring to issue https://github.com/mate-desktop/engrampa/issues/206 , Engrampa uses Libmagic only if extension is not known, otherwise it determines mime type from the file extension, even though the `--enable-magic` flag is used, along with `libmagic` support.
This pull request adds an if condition to use `libmagic` if `--enable-magic` if used.
=> Fixed libmagic bug

src/fr-archive.c
A blooper has been made there:
* if ENABLE_MIME is set, the intention was to try, in order: magic, content, filename; but it was made filename, content, magic (which was the same as before the changes);
* if ENABLE_MIME is not set, the intention was to try, in order: filename, content, magic; but it has been made magic, content, magic (notice the duplicate, and the missing "filename").
This probably doesn't change much in the wild as magic is gonna work most of the time, but it's especially problematic that the non-libmagic case doesn't have the filename test.
Anyway, fix this so the code is consistent, and we retain the behavior for the non-libmagic case, and have the new expected one for the libmagic case.
CC @sinha-toyeesh
=> Fix MIME detection logic from #490

src/fr-archive.c
MAGIC returned incorrect mime type while processing tar compression type 
Fix [492](https://github.com/mate-desktop/engrampa/issues/492)
=> priority useing get_mime_type_from_filename to obtain mime type

src/fr-command-7z.c
Offset was not properly updated when adding support for EPUB+ZIP in 84fb5cfe96263f79e50b68a5a6996e40c514cf74, leading to disabling both ZIP and RAR when the option unar-open-zip was enabled.
One can test with:
* One of the supported `7z` available (ideally with RAR support, but the error message itself is enough to see the difference)
* No (`un`)`rar` available (as it takes precedence)
* `unar` and `lsar` available (Debian package `unar`)
* Setting `gsettings set org.mate.engrampa.general unar-open-zip true`
* This patch (because if `unar` can take over it's tricky to tell):
```diff
diff --git a/src/fr-command-unarchiver.c b/src/fr-command-unarchiver.c
index c7aa5e6..0d3cf53 100644
--- a/src/fr-command-unarchiver.c
+++ b/src/fr-command-unarchiver.c
@@ -246,7 +246,7 @@ …
```
=> 7z: Fix accepting RAR archives when unar-open-zip=true

src/fr-command-zip.c
Fix crash if the `zip` command emits a line starting with one of 'd?-' yet having less than 8 fields in it, or if the date field is malformed.
Small fixed for not doing nasty things if `unzip` doesn't output what we expect.
Real test should be that it doesn't break anything, as that's what most important (although it's unused for people having one of the 7z, which is used in priority)
Convoluted test is to check what happens with random unexpected output from unzip.
What I did to test unexpected output was add a dummy `unzip` to my PATH, and get that to emit output good enough for the code to try and parse it, and bad enough to trigger issues.
For example, use this script in your PATH:
<details>
<summary><code>~/.local/bin/unzip</code></summary>
```shell
#!/bin/sh
cat << EOF
? x x 123 A X …
```
=> zip: Fix crashes on buggy zip output

src/fr-command-rar.c, src/fr-command-rar.h
This adds support for `unrar-free` as the `unrar` implementation.  Without this, at least for me on Debian with unrar-free 0.1.3, RAR archives open empty ***[edit]** while on non-Debian, unrar-free is just not used*.
There are 2 seemingly unrelated commits, but they actually change required things for the third commit to work (I could do it differently, but it'd be more messy):
* [rar: Simplify and merge duplicate code](https://github.com/mate-desktop/engrampa/commit/0d809c8d2ccb311fd51dcfddaeb8eced8b3df223) as stated in the commit message, we need the more strict RAR version matching not to erroneously match unrar-free output (which would prevent recognizing it is unrar-free, as well as reading an uninitialized variable)
* [rar: Fix out of bounds read on malformed …
=> rar: Add support for unrar-free (and related fixes)

Makefile.am
Installation with meson buildsystem works now from tarball created with `make dist`.
Btw. there is no meson.build file in /src/ui/ folder !
Not testet because i don't have any interests in using meson :P
=>  Distribute Meson build system

src/fr-command-rar.c, src/fr-command-rar.h
Fix crash with RAR 7.0 output format, e.g. without any CRC32 for directories.
This PR also starts with a more general fix to avoid crashing when failing to read a name entry, making the code more forgiving against malformed or unexpected output.
Fixes #527.
=> Fix crash with RAR 7.0
